baseURL = "https://mende.io/"
languageCode = "en-us"
title = "Tobias Mende"
theme = "coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[params]
    author = "Tobias Mende"
    info = ["Software Craftsperson", "Remote Worker", "Entrepreneur"]
    description = "Tobias Mende's personal website"
    keywords = "blog,developer,personal"
    avatarURL = "images/profile-square.jpg"
    dateFormat = "02.01.2006"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    hidecredits = false
    hidecopyright = true

    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false
    # Series see also post count
    maxSeeAlsoItems = 5
    # Enable Twemoji
    enableTwemoji = false

    custom_css = ["css/custom.css", "css/print.css"]

# Social Icons
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/TobiasMende/"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab"
    weight = 2
    url = "https://gitlab.com/TobiasMende"

[[params.social]]
    name = "StackOverflow"
    icon = "fa fa-stack-overflow"
    weight = 3
    url = "https://stackoverflow.com/users/3795833/tobiasmende"

[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 4
    url = "https://twitter.com/tobias_mende"

[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 5
    url = "https://www.linkedin.com/in/tobiasmende/"

[[params.social]]
    name = "Xing"
    icon = "fa fa-xing"
    weight = 6
    url = "https://www.xing.com/profile/Tobias_Mende/cv"

# Menu links

# [[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "/blog/"

[[menu.main]]
    name = "About"
    weight = 2
    url  = "/about/"

[[menu.main]]
    name = "CV"
    weight = 2
    url  = "/cv/"

[[menu.main]]
    name = "Imprint"
    weight = 3
    url  = "/imprint/"

[[menu.main]]
    name = "Privacy Policy"
    weight = 3
    url  = "/privacy-policy/"
